export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  };

export const userContants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
};

export const categoryConstansts = {
    GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
    ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
    UPDATE_CATEGORIES_REQUEST: "UPDATE_CATEGORIES_REQUEST",
    UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
    UPDATE_CATEGORIES_FAILURE: "UPDATE_CATEGORIES_FAILURE",
    DELETE_CATEGORIES_REQUEST: "DELETE_CATEGORIES_REQUEST",
    DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
    DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE",
  };

  export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
  
    DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
    DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
    DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",
  
    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",

    EDIT_PRODUCT_REQUEST: "EDIT_PRODUCT_REQUEST",
    EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
    EDIT_PRODUCT_FAILURE: "EDIT_PRODUCT_FAILURE",
  };

  export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
  
    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
  };

  export const CmsConstant = {
    GET_CAROUSEL_REQUEST: "GET_CAROUSEL_REQUEST",
    GET_CAROUSEL_SUCCESS: "GET_CAROUSEL_SUCCESS",
    GET_CAROUSEL_FAILURE: "GET_CAROUSEL_FAILURE",
   
    ADD_CAROUSEL_REQUEST: "ADD_CAROUSEL_REQUEST",
    ADD_CAROUSEL_SUCCESS: "ADD_CAROUSEL_SUCCESS",
    ADD_CAROUSEL_FAILURE: "ADD_CAROUSEL_FAILURE",

    UPDATE_CAROUSEL_REQUEST: "UPDATE_CAROUSEL_REQUEST",
    UPDATE_CAROUSEL_SUCCESS: "UPDATE_CAROUSEL_SUCCESS",
    UPDATE_CAROUSEL_FAILURE: "UPDATE_CAROUSEL_FAILURE",

    DELETE_CAROUSEL_REQUEST: "DELETE_CAROUSEL_REQUEST",
    DELETE_CAROUSEL_SUCCESS: "DELETE_CAROUSEL_SUCCESS",
    DELETE_CAROUSEL_FAILURE: "DELETE_CAROUSEL_FAILURE",
  }

export const TacConstants = {
    GET_TERMS_REQUEST: "GET_TERMS_REQUEST",
    GET_TERMS_SUCCESS: "GET_TERMS_SUCCESS",
    GET_TERMS_FAILURE: "GET_TERMS_FAILURE",
    
    ADD_TERMS_REQUEST: "ADD_TERMS_REQUEST",
    ADD_TERMS_SUCCESS: "ADD_TERMS_SUCCESS",
    ADD_TERMS_FAILURE: "ADD_TERMS_FAILURE",
    
    UPDATE_TERMS_REQUEST: "UPDATE_TERMS_REQUEST",
    UPDATE_TERMS_SUCCESS: "UPDATE_TERMS_SUCCESS",
    UPDATE_TERMS_FAILURE: "UPDATE_TERMS_FAILURE",
}